### ISSUE TITLE
Create an examples folder

### ISSUE THREAD

**Issue by AKS1996** [AKS1996/DiffOpt.jl#1]
include some LP, QP examples. solve them, test duality gap

**Comment by matbesancon** [comment]
you can even put these in tests to validate the progress. If something is not implemented yet you can add a `@test_broken` thing :)

**Comment by AKS1996** [comment]
yeah that'll be great!
I'll try to structure the code similar to https://github.com/cvxgrp/diffcp

**Comment by AKS1996** [comment]
began testing #3 !
