### ISSUE TITLE
Use MatrixOptInterface.jl as dependency

### ISSUE THREAD

**Issue by AKS1996** [AKS1996/DiffOpt.jl#34]
Will MatOI to generate matrices A,b,c (refer https://github.com/jump-dev/MatrixOptInterface.jl/pull/7)
This'll remove dependence on SCS.jl solver

**Comment by AKS1996** [comment]
will close once https://github.com/jump-dev/MatrixOptInterface.jl/pull/7 is closed

**Comment by AKS1996** [comment]
although will need to add MOI to LP conversion feature as @frapac suggested

**Comment by joaquimg** [comment]
Yes, but let just leave the second step as an open issue

**Comment by AKS1996** [comment]
ok. created another issue https://github.com/jump-dev/MatrixOptInterface.jl/issues/8
