### ISSUE TITLE
changing the directory structure

### ISSUE THREAD

**Issue by AKS1996** [AKS1996/DiffOpt.jl#5]
although the repo is lacking features to actually begin differentiating, somewhere down the lane the structure should resemble
- https://github.com/locuslab/qpth/blob/master/qpth/qp.py
- https://github.com/cvxgrp/diffcp/blob/master/diffcp/cone_program.py

**Comment by AKS1996** [comment]
the solving/forward part is easy, we need not expose a method for it. 
but better have callable methods for finding derivative and adjoint derivative (assuming current focus non QPs 1st, then conic programs)

**Comment by matbesancon** [comment]
one thing you can add is travis on the examples:
it needs adding a new line
```julia
- julia --project example/your_file1.jl'
- julia --project example/your_file2.jl'
```
in the `after_success:` bloc.

See this example:
https://github.com/SCIP-Interfaces/SCIP.jl/blob/master/.travis.yml#L49

**Comment by AKS1996** [comment]
including examples in #10
